#!/bin/zsh
# This hook is run after a new virtualenv is activated.

if [ -e /usr/local/lib/python2.7/site-packages/IPython ]; then
  ln -s /usr/local/lib/python2.7/site-packages/IPython "${VIRTUAL_ENV}/lib/python2.7/site-packages"
  ln -s /usr/local/lib/python2.7/site-packages/ipython-*.egg-info "${VIRTUAL_ENV}/lib/python2.7/site-packages"
fi
