#!/usr/bin/env zsh
# This hook is run after every virtualenv is activated.

PS1="$_OLD_VIRTUAL_PS1"
_OLD_STATIC_RPROMPT="$STATIC_RPROMPT"
STATIC_RPROMPT="%{${fg_bold[white]}%}[%{${fg[green]}%}`basename \"$VIRTUAL_ENV\"`%{${fg_bold[white]}%}]%{${reset_color}%} $_OLD_STATIC_RPROMPT"

